### ISSUE TITLE
Improve rest api validation

### ISSUE THREAD

**Issue by svetoslavpetkov** [smilenll/rentalCarApp#5]
General rules:
not found objects should return status 404 (NotFound) and meaningful message
wrong input for example return car with date in the past should return status 400 (BadRequest)
All other errors should return 500 (ServerError) and meaningful message

Reasonable validations:
Create contract
    with wrong pick-up and or return dates
    on none existing car
    on car that already has running contract
Return car
    on not existing contract

You may think of more

**Comment by smilenll** [comment]
I create two new Error handling filters ValidationError NotFoundError

**Comment by svetoslavpetkov** [comment]
Common isssues:
- On some places you throw NotFoundError, on other you throw new SystemError('Car not found.', 404). Use one aproach
- You do not use the ValidationError at all


Found issues:
1. getCars() , should not throw 404 if no cars, jsut return empty list
2. getOpenContracts, should not throw NotFoundError is no contracts found

Missing validations:
- What happens if tyr to get car with id="abcdefg", do we handle that
- What happens if I try to create contract on car wiht id="abcdefg", do we handle that
- What happens if I try to create contract with initialDate="SegaGoiskam"
- What happens if I try to returnCar on conract with contractId="abcdefg" 
- There are more to be valedated - go through code again

**Comment by svetoslavpetkov** [comment]
Great looks much better now. I have two more thing this to be professional:

I see that on each controller method a list of possible exceptions is handled by @UseFilters(ValidationErrorFilter), this is a bad practise because:
1: the controller method does not know what exceptions can be thrown
2: If a new exceptions are introduced (for example AuthenticationError and UnauthorisedError), then we should go and make changes all the controllers to add that handler
Solution is to use global filter(s) for exception handling 


As addition use Errors inheritance and handle errors in a common way.
